/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitasIndexRouteImport } from './routes/visitas.index'
import { Route as PermisosIndexRouteImport } from './routes/permisos.index'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as InmueblesIndexRouteImport } from './routes/inmuebles.index'
import { Route as ContactosIndexRouteImport } from './routes/contactos.index'
import { Route as ComercialesIndexRouteImport } from './routes/comerciales.index'
import { Route as CarteraIndexRouteImport } from './routes/cartera.index'
import { Route as BandejaIndexRouteImport } from './routes/bandeja.index'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as InmueblesIdRouteImport } from './routes/inmuebles.$id'
import { Route as ApiGoogleCalendarConnectRouteImport } from './routes/api.google-calendar.connect'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api.google-calendar.callback'

const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitasIndexRoute = VisitasIndexRouteImport.update({
  id: '/visitas/',
  path: '/visitas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PermisosIndexRoute = PermisosIndexRouteImport.update({
  id: '/permisos/',
  path: '/permisos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const InmueblesIndexRoute = InmueblesIndexRouteImport.update({
  id: '/inmuebles/',
  path: '/inmuebles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosIndexRoute = ContactosIndexRouteImport.update({
  id: '/contactos/',
  path: '/contactos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialesIndexRoute = ComercialesIndexRouteImport.update({
  id: '/comerciales/',
  path: '/comerciales/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/comerciales.index.lazy').then((d) => d.Route),
)
const CarteraIndexRoute = CarteraIndexRouteImport.update({
  id: '/cartera/',
  path: '/cartera/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaIndexRoute = BandejaIndexRouteImport.update({
  id: '/bandeja/',
  path: '/bandeja/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const InmueblesIdRoute = InmueblesIdRouteImport.update({
  id: '/inmuebles/$id',
  path: '/inmuebles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarConnectRoute =
  ApiGoogleCalendarConnectRouteImport.update({
    id: '/api/google-calendar/connect',
    path: '/api/google-calendar/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/agenda/': typeof AgendaIndexRoute
  '/bandeja/': typeof BandejaIndexRoute
  '/cartera/': typeof CarteraIndexRoute
  '/comerciales/': typeof ComercialesIndexRoute
  '/contactos/': typeof ContactosIndexRoute
  '/inmuebles/': typeof InmueblesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/permisos/': typeof PermisosIndexRoute
  '/visitas/': typeof VisitasIndexRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/agenda': typeof AgendaIndexRoute
  '/bandeja': typeof BandejaIndexRoute
  '/cartera': typeof CarteraIndexRoute
  '/comerciales': typeof ComercialesIndexRoute
  '/contactos': typeof ContactosIndexRoute
  '/inmuebles': typeof InmueblesIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/permisos': typeof PermisosIndexRoute
  '/visitas': typeof VisitasIndexRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/agenda/': typeof AgendaIndexRoute
  '/bandeja/': typeof BandejaIndexRoute
  '/cartera/': typeof CarteraIndexRoute
  '/comerciales/': typeof ComercialesIndexRoute
  '/contactos/': typeof ContactosIndexRoute
  '/inmuebles/': typeof InmueblesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/permisos/': typeof PermisosIndexRoute
  '/visitas/': typeof VisitasIndexRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/restablecer-contrasena'
    | '/inmuebles/$id'
    | '/agenda/'
    | '/bandeja/'
    | '/cartera/'
    | '/comerciales/'
    | '/contactos/'
    | '/inmuebles/'
    | '/perfil/'
    | '/permisos/'
    | '/visitas/'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/restablecer-contrasena'
    | '/inmuebles/$id'
    | '/agenda'
    | '/bandeja'
    | '/cartera'
    | '/comerciales'
    | '/contactos'
    | '/inmuebles'
    | '/perfil'
    | '/permisos'
    | '/visitas'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/restablecer-contrasena'
    | '/inmuebles/$id'
    | '/agenda/'
    | '/bandeja/'
    | '/cartera/'
    | '/comerciales/'
    | '/contactos/'
    | '/inmuebles/'
    | '/perfil/'
    | '/permisos/'
    | '/visitas/'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  InmueblesIdRoute: typeof InmueblesIdRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  BandejaIndexRoute: typeof BandejaIndexRoute
  CarteraIndexRoute: typeof CarteraIndexRoute
  ComercialesIndexRoute: typeof ComercialesIndexRoute
  ContactosIndexRoute: typeof ContactosIndexRoute
  InmueblesIndexRoute: typeof InmueblesIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  PermisosIndexRoute: typeof PermisosIndexRoute
  VisitasIndexRoute: typeof VisitasIndexRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiGoogleCalendarConnectRoute: typeof ApiGoogleCalendarConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitas/': {
      id: '/visitas/'
      path: '/visitas'
      fullPath: '/visitas/'
      preLoaderRoute: typeof VisitasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permisos/': {
      id: '/permisos/'
      path: '/permisos'
      fullPath: '/permisos/'
      preLoaderRoute: typeof PermisosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmuebles/': {
      id: '/inmuebles/'
      path: '/inmuebles'
      fullPath: '/inmuebles/'
      preLoaderRoute: typeof InmueblesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/': {
      id: '/contactos/'
      path: '/contactos'
      fullPath: '/contactos/'
      preLoaderRoute: typeof ContactosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comerciales/': {
      id: '/comerciales/'
      path: '/comerciales'
      fullPath: '/comerciales/'
      preLoaderRoute: typeof ComercialesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartera/': {
      id: '/cartera/'
      path: '/cartera'
      fullPath: '/cartera/'
      preLoaderRoute: typeof CarteraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja/': {
      id: '/bandeja/'
      path: '/bandeja'
      fullPath: '/bandeja/'
      preLoaderRoute: typeof BandejaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmuebles/$id': {
      id: '/inmuebles/$id'
      path: '/inmuebles/$id'
      fullPath: '/inmuebles/$id'
      preLoaderRoute: typeof InmueblesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/connect': {
      id: '/api/google-calendar/connect'
      path: '/api/google-calendar/connect'
      fullPath: '/api/google-calendar/connect'
      preLoaderRoute: typeof ApiGoogleCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  InmueblesIdRoute: InmueblesIdRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  BandejaIndexRoute: BandejaIndexRoute,
  CarteraIndexRoute: CarteraIndexRoute,
  ComercialesIndexRoute: ComercialesIndexRoute,
  ContactosIndexRoute: ContactosIndexRoute,
  InmueblesIndexRoute: InmueblesIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  PermisosIndexRoute: PermisosIndexRoute,
  VisitasIndexRoute: VisitasIndexRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiGoogleCalendarConnectRoute: ApiGoogleCalendarConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
