/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SilviaIndexRouteImport } from './routes/silvia.index'
import { Route as InmueblesIndexRouteImport } from './routes/inmuebles.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as AlquileresIndexRouteImport } from './routes/alquileres.index'
import { Route as InmueblesIdRouteImport } from './routes/inmuebles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SilviaIndexRoute = SilviaIndexRouteImport.update({
  id: '/silvia/',
  path: '/silvia/',
  getParentRoute: () => rootRouteImport,
} as any)
const InmueblesIndexRoute = InmueblesIndexRouteImport.update({
  id: '/inmuebles/',
  path: '/inmuebles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlquileresIndexRoute = AlquileresIndexRouteImport.update({
  id: '/alquileres/',
  path: '/alquileres/',
  getParentRoute: () => rootRouteImport,
} as any)
const InmueblesIdRoute = InmueblesIdRouteImport.update({
  id: '/inmuebles/$id',
  path: '/inmuebles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/alquileres/': typeof AlquileresIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/inmuebles/': typeof InmueblesIndexRoute
  '/silvia/': typeof SilviaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/alquileres': typeof AlquileresIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/inmuebles': typeof InmueblesIndexRoute
  '/silvia': typeof SilviaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/alquileres/': typeof AlquileresIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/inmuebles/': typeof InmueblesIndexRoute
  '/silvia/': typeof SilviaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inmuebles/$id'
    | '/alquileres/'
    | '/clientes/'
    | '/inmuebles/'
    | '/silvia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inmuebles/$id'
    | '/alquileres'
    | '/clientes'
    | '/inmuebles'
    | '/silvia'
  id:
    | '__root__'
    | '/'
    | '/inmuebles/$id'
    | '/alquileres/'
    | '/clientes/'
    | '/inmuebles/'
    | '/silvia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InmueblesIdRoute: typeof InmueblesIdRoute
  AlquileresIndexRoute: typeof AlquileresIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  InmueblesIndexRoute: typeof InmueblesIndexRoute
  SilviaIndexRoute: typeof SilviaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silvia/': {
      id: '/silvia/'
      path: '/silvia'
      fullPath: '/silvia/'
      preLoaderRoute: typeof SilviaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmuebles/': {
      id: '/inmuebles/'
      path: '/inmuebles'
      fullPath: '/inmuebles/'
      preLoaderRoute: typeof InmueblesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alquileres/': {
      id: '/alquileres/'
      path: '/alquileres'
      fullPath: '/alquileres/'
      preLoaderRoute: typeof AlquileresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmuebles/$id': {
      id: '/inmuebles/$id'
      path: '/inmuebles/$id'
      fullPath: '/inmuebles/$id'
      preLoaderRoute: typeof InmueblesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InmueblesIdRoute: InmueblesIdRoute,
  AlquileresIndexRoute: AlquileresIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  InmueblesIndexRoute: InmueblesIndexRoute,
  SilviaIndexRoute: SilviaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
