/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InmueblesIndexRouteImport } from './routes/inmuebles.index'
import { Route as InmueblesIdRouteImport } from './routes/inmuebles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InmueblesIndexRoute = InmueblesIndexRouteImport.update({
  id: '/inmuebles/',
  path: '/inmuebles/',
  getParentRoute: () => rootRouteImport,
} as any)
const InmueblesIdRoute = InmueblesIdRouteImport.update({
  id: '/inmuebles/$id',
  path: '/inmuebles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/inmuebles/': typeof InmueblesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/inmuebles': typeof InmueblesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inmuebles/$id': typeof InmueblesIdRoute
  '/inmuebles/': typeof InmueblesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inmuebles/$id' | '/inmuebles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inmuebles/$id' | '/inmuebles'
  id: '__root__' | '/' | '/inmuebles/$id' | '/inmuebles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InmueblesIdRoute: typeof InmueblesIdRoute
  InmueblesIndexRoute: typeof InmueblesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmuebles/': {
      id: '/inmuebles/'
      path: '/inmuebles'
      fullPath: '/inmuebles/'
      preLoaderRoute: typeof InmueblesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmuebles/$id': {
      id: '/inmuebles/$id'
      path: '/inmuebles/$id'
      fullPath: '/inmuebles/$id'
      preLoaderRoute: typeof InmueblesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InmueblesIdRoute: InmueblesIdRoute,
  InmueblesIndexRoute: InmueblesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
